### ISSUE TITLE
API breaking changes to distributions, images and volumes

### ISSUE THREAD

**Issue by rmcintosh** [archiecobbs/linode-apiv4-java#1]
https://developers.linode.com/v4/changelogs

**Comment by archiecobbs** [comment]
Thanks.

If they would keep their API documentation up to date this would be a lot easier... there are still tons of inconsistencies.

**Comment by howdiz** [comment]
Hi @archiecobbs. Sorry for the inconvenience. Is there a specific inconsistency you've noticed, that should be addressed?

**Comment by archiecobbs** [comment]
Frankly there are too many to list them all. My recommendation is some kind of exhaustive review or better tools to automate the API documentation.

Here are just a few that I've noted. Note some may have changed due to the recent release.

In the "Example JSON Response Body" for GET https://developers.linode.com/v4/reference/endpoints/linode/instances/$id, we see this:

backups.last_backup.finished: "2015-09-29T11:21:01"

and this:

distribution.updated: "2016-12-24T18:00:09.000Z"

Note one has milliseconds and timezone, while the other doesn't. But in fact, in my testing, it appears that the documentation is completely wrong about the "distribution" property anyway: it's a string, not an object.

several fields are not documented as format and/or possible values:

Backup.status
Backup.type
Backup.availability
Linode.backups.service.updated

The response to /linode/instances/$id/backups is not paginated, but it is documented as such.

/images response is paginated, but it is not documented as such.

Image.status possible values are not documented.

Image.type possible values are not documented.

Linode.backups.schedule.day is not documented as to possible values.

Distribution.vendor is marked filterable but API returns "Cannot filter on vendor"

Etc. etc.

**Comment by howdiz** [comment]
Thanks for the feedback @archiecobbs . We'll look into these specifics issues and review the rest of the docs as well.

**Comment by archiecobbs** [comment]
@howdiz here are some additional documentation issues from my notes.
```
- /linode/instances/$id
    GET > Response > image
        Value is String, not object
    GET > Response > created
        Value is Datetime, not String
        Not documented
    GET > Response > backups > last_backup > status
        Wrong values for enum (apply to Linode, not backup)
    GET > Response > backups > snapshot > status
        Wrong values for enum (apply to Linode, not backup)
    GET > Response > image > status
        Wrong values for enum (apply to Linode, not image)

- /linode/types/$id
    GET > Response > price > monthly
        Value is Float, not Integer
    GET > Response > addons > backups > price > monthly
        Value is Float, not Integer

- /linode/images

    Filtering on fields claiming to be "filterable" doesn't work, for example:
       INPUT: X-Filter: {"+and":[{"public":true},{"vendor":"Debian"}],"+order":"asc","+order_by":"label"}
      OUTPUT: 400 BAD REQUEST
            {"errors": [
                {"reason": "Cannot filter on public", "field": "X-Filter"},
                {"reason": "Cannot filter on vendor", "field": "X-Filter"}
            ]}

- /linode/images/$id
    GET > Response > type
        Values are not "0" and "1". I've seen only "manual". What's the other value??
    GET > Response > deprecated
        This field is present in API response but not documented

- /linodes/instances/$id/ips
    GET > Response > ipv6 > slaac
        Typo: "SLACC range" should be "SLAAC range"

```

**Comment by archiecobbs** [comment]
Updated to 2017-12-11 API in 0efe4371.

**Comment by SzySteve** [comment]
Hey @archiecobbs thanks very much for the notes above: We've addressed them and they will go live in our next release along with other cleanup items. If you come across any more please feel free to reach out!
